name: Rust CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build_core_and_cli:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy
    
    - name: Fix code style issues
      run: |
        # Fix redundant field names in struct initialization
        sed -i 's/public_key: public_key,/public_key,/g' quietdrop-cli/src/main.rs
        sed -i 's/public_key: public_key,/public_key,/g' quietdrop-core/src/main.rs
        # Fix test imports
        find quietdrop-core/tests -type f -name "*.rs" -exec sed -i 's/use quietdrop::/use quietdrop_core::/g' {} \;
    
    - name: Build core library
      run: cargo build -p quietdrop-core
    
    - name: Build CLI
      run: cargo build -p quietdrop-cli
    
    - name: Lint code
      run: cargo clippy -p quietdrop-core -p quietdrop-cli -- -D warnings
    
    - name: Run tests for core
      run: cargo test -p quietdrop-core --lib